[package]
name = "deep-glue-clap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
deep-dsp = { path = "../../crates/deep-dsp" }
deep-metering = { path = "../../crates/deep-metering" }
deep-params = { path = "../../crates/deep-params" }
clack-plugin.workspace = true
clack-extensions = { workspace = true, features = ["audio-ports", "params", "state", "clack-plugin"] }
